# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CloudList', '0001_initial'),
        ('AccountSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('cmpid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
                ('notes', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=300)),
                ('fee', models.FloatField()),
                ('typeid', models.IntegerField()),
                ('itemList', models.CharField(max_length=200)),
                ('state', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('paid_time', models.DateTimeField()),
                ('finish_time', models.DateTimeField()),
                ('prepayid', models.CharField(max_length=50)),
                ('signature', models.CharField(max_length=50)),
                ('showid', models.CharField(max_length=50)),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudList.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountSystem.User')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='VIPOrder',
            fields=[
                ('void', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('level', models.IntegerField()),
                ('prepayid', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountSystem.User')),
            ],
            options={
                'db_table': 'order_vip',
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrderSystem.Order'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountSystem.User'),
        ),
    ]
