# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CloudList.Address'),
        ),
    ]
