# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderSystem', '0002_auto_20160724_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finish_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
