# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('acid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
                ('typename', models.CharField(max_length=50)),
                ('priority', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
                ('bannerurl', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('dsid', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.CharField(max_length=300)),
                ('code', models.CharField(max_length=50)),
                ('showcode', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=300)),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fdid', models.AutoField(primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=300)),
                ('state', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountSystem.User')),
            ],
            options={
                'db_table': 'feedbacks',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('vrid', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('state', models.IntegerField()),
                ('typeid', models.IntegerField()),
                ('compulsorylist', models.CharField(max_length=300)),
                ('selectlist', models.CharField(max_length=300)),
                ('compulsorynotes', models.CharField(max_length=300)),
                ('notes', models.CharField(max_length=300)),
                ('devnotes', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'meta_version',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AssistSystem.Discount'),
        ),
    ]
