# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AssistSystem', '0010_version_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='typename',
            field=models.CharField(default='png', max_length=50),
            preserve_default=False,
        ),
    ]
