# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('adid', models.AutoField(primary_key=True, serialize=False)),
                ('addr', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.IntegerField()),
                ('is_default', models.IntegerField()),
                ('tagid', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('ctid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('cmid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'communities',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('dsid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city_belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudList.City')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=200)),
                ('time_saved', models.DateTimeField()),
                ('state', models.IntegerField()),
                ('typeid', models.IntegerField()),
                ('subtype_name', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('gender', models.IntegerField()),
                ('avatar', models.IntegerField()),
                ('present_id', models.IntegerField(default=None, null=True)),
                ('user_belong_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountSystem.User')),
            ],
            options={
                'db_table': 'things',
            },
        ),
        migrations.CreateModel(
            name='WareHouse',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('addr', models.CharField(max_length=200)),
                ('typeid', models.IntegerField()),
            ],
            options={
                'db_table': 'warehouses',
            },
        ),
        migrations.AddField(
            model_name='thing',
            name='wh_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudList.WareHouse'),
        ),
        migrations.AddField(
            model_name='community',
            name='district_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudList.District'),
        ),
        migrations.AddField(
            model_name='community',
            name='wh_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudList.WareHouse'),
        ),
        migrations.AddField(
            model_name='address',
            name='community_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CloudList.Community'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountSystem.User'),
        ),
    ]
