# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VIPSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('phone', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
            ],
            options={
                'db_table': 'code_by_phone',
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('icid', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'meta_invite',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.IntegerField()),
                ('nickname', models.CharField(max_length=200)),
                ('gender', models.IntegerField()),
                ('birthday', models.CharField(max_length=50)),
                ('register', models.DateTimeField()),
                ('lastLogin', models.DateTimeField()),
                ('loginIp', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('avatar', models.IntegerField()),
                ('username', models.CharField(default=b'WEIRDUSER', max_length=100)),
                ('vip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VIPSystem.VIP')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('session_password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_session',
            },
        ),
    ]
