# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VIPSystem.VIP'),
        ),
    ]
