# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VIPSystem', '0004_auto_20160719_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vip',
            name='headPackage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='VIPSystem.VIPPackage'),
        ),
        migrations.AlterField(
            model_name='vippackage',
            name='nextPackage',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='VIPSystem.VIPPackage'),
        ),
        migrations.AlterField(
            model_name='vippackage',
            name='start_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
